<?php

namespace Components\Account\RollingReserve;

use Components\Account\AbstractAccount;
use Components\Account\AccountInterface;
use Constants\AccountCode;
use Constants\AccountGeneral;
use Constants\AccountType;
use DateTime;
use Models\Account\Reserve\ReserveAccountInfo;
use Models\Account\RollingReserve\RollingReserveAccount as RollingReserveAccountModel;
use Models\Account\RollingReserve\RollingReserveAccountInfo;
use Models\Account\RollingReserve\RollingReserveAccountTransaction;

/**
 * Class RollingReserveAccount
 * @package Components\Account
 */
class RollingReserveAccount extends AbstractAccount
{
    /**
     * {@inheritdoc}
     */
    public function __construct($accountEntity, $currency)
    {
        parent::__construct($accountEntity, $currency);
        $this->accountInfoModel = $this->modelLoader->load(RollingReserveAccountInfo::class, true);
        $this->accountTransactionModel = $this->modelLoader->load(RollingReserveAccountTransaction::class, true);
        $this->accountModel = $this->modelLoader->load(RollingReserveAccountModel::class, true);
    }

    /**
     * Returns constant par account type ID for the respective account.
     * This function will have to be implemented in every child.
     *
     * @return int
     */
    public function getAccountType()
    {
        return AccountType::ROLLING_RESERVE_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountCode()
    {
        return AccountCode::ROLLING_RESERVE_ACCOUNT;
    }

    /**
     * {@inheritdoc}
     */
    protected function isAccountNeeded($config)
    {
        //if reserve taken for this merchant, have reserve acc from outlet level (check take_reserve_flag and also match type of reserve)
        $take_reserves = (bool) ($config['merchant']['take_reserves_flag'] ?? 0);
        $rolling = (isset($config['config']['reserve_type']) ? ($config['config']['reserve_type'] == AccountGeneral::RESERVE_TYPE_ROLLING) : false);
        return $take_reserves && $rolling;
    }

    /**
     * Update today's account info's reserved_today field,
     * using the passed additional reserved amount.
     * If there is no account info for today, create it.
     *
     * @author Adrian
     * @since 2.0.0
     * @date_created 2019-08-01
     *
     * @param float $additional_reserved_amount
     *
     * @return float full reserved today amount
     * @throws \Core\Exceptions\ApiException
     */
    public function updateReservedToday($additional_reserved_amount)
    {
        //lazy load
        $accountInfo = $this->getAccountInfo();

        //get DateTime for both dates on midnight, so we can diff
        $today = new DateTime();
        $latest = new DateTime($accountInfo->date_added);
        $today->setTime(0, 0);
        $latest->setTime(0, 0);

        //if there is at least 1 day difference, create a new account info
        if ($today->diff($latest)->days != 0) {
            $accountInfo = $this->createAccountInfo($accountInfo->balance, $accountInfo->info_balance);
        }

        /* @var ReserveAccountInfo $accountInfo */
        $accountInfo->reserved_today += $additional_reserved_amount;
        $accountInfo->save();

        return $accountInfo->reserved_today;
    }

    public function debit(AccountInterface $to, float $amount, int $transaction_category_id = NULL, $directive_instruction = false, $description = null)
    {
        //TODO we need an override here:
        // for moving sideways, to release/deduction:
        // get all UNprocesed account infos, their total in should add up to balance
        // bit by bit update their settled_amount from oldest to newest, until amount to be moved was reached

        parent::debit($to, $amount, $transaction_category_id, $directive_instruction); // TODO: Change the autogenerated stub
    }
}